### ISSUE TITLE
How to use batch operations in maleorang

### ISSUE THREAD

**Issue by mayorcoded** [Ecwid/maleorang#18]
Hi, thanks for your great job on this wrapper. Please how do I use this wrapper for batch operations, the implementations seems quite complicated? Any doc for this? Expecting your reply

**Comment by basiliscus** [comment]
Hi @mayorcoded ,
You can see an example [here](https://github.com/Ecwid/maleorang/blob/master/src/test/java/com/ecwid/maleorang/method/v3_0/batches/BatchTest.kt).
