### ISSUE TITLE
Unable to use Batch operation with MailchimpClient

### ISSUE THREAD

**Issue by mayorcoded** [Ecwid/maleorang#19]
Hi guys, please I a get an error each time I pass a StartBatchOperations object to the client.execute() method in java, but this works well in the kotlin test, can I get a help on why this happens and what I can do? see pictures below:

This is the java error I get
![java error](https://user-images.githubusercontent.com/17001801/30692353-180df7f6-9ec3-11e7-84ba-484920ede06c.JPG)
This is the same implementation in Kotlin without errors
![kotlin](https://user-images.githubusercontent.com/17001801/30692392-41726c4e-9ec3-11e7-9aa8-95d4349518b9.JPG)

**Comment by basiliscus** [comment]
Hi @mayorcoded ,

Can you copy and paste the java code here?

**Comment by mayorcoded** [comment]
`package com.jumia.updateList;

/**
 * Created by DELL on 2/9/2017.
 */

import com.ecwid.maleorang.MailchimpClient;

import com.ecwid.maleorang.MailchimpMethod;
import com.ecwid.maleorang.MailchimpObject;

import com.ecwid.maleorang.method.v3_0.batches.StartBatchMethod;
import com.ecwid.maleorang.method.v3_0.lists.members.EditMemberMethod;
import com.ecwid.maleorang.method.v3_0.lists.members.MemberInfo;


import org.dom4j.Document;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;

import java.io.BufferedReader;
import java.io.InputStreamReader;

import java.net.URL;
import java.net.URLConnection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.ForkJoinPool;


public class AffiliateListUpdater {
    
    private static final String apiKey = "" ,listId = "";
    private static final DateFormat df = new SimpleDateFormat("MM-dd-yyyy");

    public static void main(String[] args) throws Exception {

        int start = 290, rounds = 291, listlength;


        Calendar calendar = Calendar.getInstance();
        final String endDate = String.valueOf(df.format(calendar.getTime()));

        calendar.add(Calendar.DAY_OF_MONTH, -29);
        final String startDate = String.valueOf(df.format(calendar.getTime()));

        List<Integer> startPoints = new LinkedList<>();

        for(int i = start; i <= rounds;i++){
            startPoints.add(i * 100);
        }
        /*
        ForkJoinPool updateListPool = new ForkJoinPool(1);
        Thread thread = new Thread(()-> updateListPool.submit(() -> {
                startPoints.parallelStream().forEach( n -> {
                    try{
                        getAffiliatesFromCakeAndUpdateList(n, startDate, endDate);
                    }catch (Exception e){}
                });
            }).invoke()
        );
        thread.start();
        */
        getAffiliatesFromCakeAndUpdateList(29300, startDate, endDate);


        //System.out.println(startPoints.toString());

    }

    public static void updateMailchimpList(String aid, String fn, String ln, String email, String cn, String tag) throws Exception{

        MailchimpClient client = new MailchimpClient(apiKey);
        try {
            EditMemberMethod.CreateOrUpdate method = new EditMemberMethod.CreateOrUpdate(listId, email);
            method.status = "subscribed";
            method.merge_fields = new MailchimpObject();

            method.merge_fields.mapping.put("FNAME", fn);
            method.merge_fields.mapping.put("LNAME", ln);
            method.merge_fields.mapping.put("COUNTRY", cn);
            method.merge_fields.mapping.put("TAG", tag);
            method.merge_fields.mapping.put("AID", aid);
            method.merge_fields.mapping.put("NG_ACTIVE", "0");
            method.merge_fields.mapping.put("KE_ACTIVE", "0");
            method.merge_fields.mapping.put("EG_ACTIVE", "0");
            method.merge_fields.mapping.put("MA_ACTIVE", "0");
            method.merge_fields.mapping.put("GH_ACTIVE", "0");
            method.merge_fields.mapping.put("CI_ACTIVE", "0");
            method.merge_fields.mapping.put("CA_ACTIVE", "0");
            method.merge_fields.mapping.put("TVL_ACTIVE", "0");
            method.merge_fields.mapping.put("ACTIVE_ONE", "0");
            method.merge_fields.mapping.put("ACTIV_MANY", "0");
            //Engaged Fields
            method.merge_fields.mapping.put("NG_ENGAGED", "0");
            method.merge_fields.mapping.put("KE_ENGAGED", "0");
            method.merge_fields.mapping.put("EG_ENGAGED", "0");
            method.merge_fields.mapping.put("MA_ENGAGED", "0");
            method.merge_fields.mapping.put("GH_ENGAGED", "0");
            method.merge_fields.mapping.put("CI_ENGAGED", "0");
            method.merge_fields.mapping.put("CA_ENGAGED", "0");
            method.merge_fields.mapping.put("TVL_ENGAGE", "0");


            MemberInfo member = client.execute(method);
            System.out.println("The user has been successfully subscribed: " + member);

            int offerId[] = {7,8,9,10,11,13,15,16};
            for (int i = 0; i < offerId.length; i++) {
                getTotalLiteClicksAndUpdateEngagement(aid,offerId[i], email);
            }

        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
        }finally {
            client.close();
        }
    }

    public static int getAffiliatesFromCakeAndUpdateList(int start,String startDate, String endDate){

        String cakeapi = "";
        System.out.println(cakeapi);
        String affiliate_id = "", country = "", first_name = "", last_name = "", email = "", affiliate_tag = "Local";
        List<Node> list = new LinkedList<>();
        try {
            URL cake = new URL(cakeapi);

            URLConnection query = cake.openConnection();
            BufferedReader data = new BufferedReader( new InputStreamReader(query.getInputStream()));

            SAXReader reader = new SAXReader();
            Document document = reader.read(data);
            //System.out.print(document.asXML());
            list =  document.selectNodes("/*[name()='affiliate_export_response']/*[name()='affiliates']/*[name()='affiliate']");
            System.out.println(list.size());

            for (Node item: list) {
                String value = item.asXML();
                affiliate_id = value.substring(value.indexOf("<affiliate_id>") + 14,value.indexOf("</affiliate_id>"));

                int cnStart = value.indexOf("<country>"), cnStop = value.indexOf("</country>");
                int fnStart = value.indexOf("<first_name>"), fnStop = value.indexOf("</first_name>");
                int lnStart = value.indexOf("<last_name>"), lnStop = value.indexOf("</last_name>");
                int eStart = value.indexOf("<email_address>"), eStop = value.indexOf("</email_address");
                int tStart = value.indexOf("<tag_name"), tStop = value.indexOf("</tag_name>");

                country = (cnStart != -1 && cnStop != -1)? value.substring(cnStart + 9,cnStop): "";
                first_name = (fnStart != -1 && fnStop != -1)? value.substring(fnStart + 12,fnStop): "";
                last_name = (lnStart != -1 && lnStop != -1)? value.substring(lnStart + 11,lnStop): "";
                email = (eStart != -1 && eStop != -1)? value.substring(eStart + 15,eStop): "";
                affiliate_tag = (tStart != -1 && tStop != -1)? value.substring(tStart + 36,tStop): "Local";

                updateMailchimpList(affiliate_id, first_name, last_name, email, country, affiliate_tag);
                //getCakeClicksAndUpdateActiveOffer(affiliate_id,startDate, endDate, email);
            }

            data.close();

        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }

        return list.size();
    }

    private static void getCakeClicksAndUpdateActiveOffer(String aid, String startDate, String endDate, String email){
        System.out.println(startDate + " => " + endDate);
        String cakeapi = "";
        System.out.println(cakeapi);
        String affiliate_id = "", affiliate_name = "Local", offer_name  = "", total_paid, conversions ="";

        HashMap< String,String > country = new HashMap<>();
        country.put("Jumia Nigeria","NG");
        country.put("Jumia Egypt", "EG");
        country.put("Jumia Morocco", "MA");
        country.put("Jumia Travel", "TRVL");
        country.put("Jumia Kenya", "KE");
        country.put("Jumia Cameroon", "CM");
        country.put("Jumia Ghana","GH");
        country.put("Jumia Ivory Coast", "CI");

        try {
            URL cake = new URL(cakeapi);
            URLConnection query = cake.openConnection();
            BufferedReader data = new BufferedReader( new InputStreamReader(query.getInputStream()));
            SAXReader reader = new SAXReader();
            Document document = reader.read(data);


            List<Node> list =  document.selectNodes("/*[name()='campaign_summary_response']/*[name()='campaigns']/*[name()='campaign_summary']");
            int count = 0;
            for (Node item: list) {
                String value = item.asXML();

                int idStart = value.indexOf("<source_affiliate_id xmlns="), idStop = value.indexOf("</source_affiliate_id>");
                int nameStart = value.indexOf("<source_affiliate_name xmlns="), nameStop = value.indexOf("</source_affiliate_name");
                int offerStart = value.indexOf("<site_offer_name xmlns="), offerStop = value.indexOf("</site_offer_name>");
                int totalStart = value.indexOf("<total_paid>"), totalStop = value.indexOf("</total_paid");
                int convStart = value.indexOf("<macro_event_conversions>"), convStop = value.indexOf("</macro_event_conversions>");

                affiliate_id = (idStart != -1 && idStop != -1) ? value.substring(idStart + 47, idStop) : "";
                affiliate_name = (nameStart != -1 && nameStop != -1) ? value.substring(nameStart + 49, nameStop) : "";
                offer_name = (offerStart != -1 && offerStop != -1) ? value.substring(offerStart + 43, offerStop) : "";
                total_paid = (totalStart != -1 && totalStop != -1) ? value.substring(totalStart + 12, totalStop) : "0.0";
                conversions = (convStart != -1 && convStop != -1) ? value.substring(convStart + 25, convStop) : "0.0";

                if (Double.valueOf(total_paid) > 0 || Double.valueOf(conversions) > 0) {
                    updateMailchimpListOffer(email, country.get(offer_name));
                }

            }

            data.close();
            System.out.println("list size: " + list.size());
        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
            //getCakeClicks(startDate,endDate);
        }
        finally {

        }
    }

    private static void getTotalLiteClicksAndUpdateEngagement(String aid,int offerId, String email ){

        //Get required date
        String startDate, endDate;
        Calendar calendar = Calendar.getInstance();
        endDate = String.valueOf(df.format(calendar.getTime()));

        calendar.add(Calendar.DAY_OF_MONTH, -29);
        startDate = String.valueOf(df.format(calendar.getTime()));

        //System.out.println(startDate + " => " + endDate);
        String cakeapi = "";

        //System.out.println(cakeapi);
        try {
            int totalClicks = 0;
            URL cake = new URL(cakeapi);
            URLConnection query = cake.openConnection();
            BufferedReader data = new BufferedReader( new InputStreamReader(query.getInputStream()));
            SAXReader reader = new SAXReader();
            Document document = reader.read(data);

            //System.out.print(document.asXML());
            List<Node> list =  document.selectNodes("/*[name()='ArrayOfDailySummary']/*[name()='DailySummary']");
            //System.out.println(list.size());
            for (Node item: list) {
                String value = item.asXML();

                int clickStart = value.indexOf("<total_lite_clicks>"), clickStop = value.indexOf("</total_lite_clicks>");

                String totalClickValue = (clickStart != -1 && clickStop != -1) ? value.substring(clickStart+ 19, clickStop) : "";
                if(totalClickValue.length() > 0) totalClicks  += Integer.parseInt(totalClickValue);


                if ( totalClicks > 0) {
                    updateMailchimpListOfferEngagement(offerId, email);
                }
            }
            System.out.println(totalClicks);
            data.close();
        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
            //getCakeClicks(startDate,endDate);
        }
        finally {

        }
    }

    private static String getEmail(String id){
        String cakeapi = "";
        String email = "";
        try {
            URL cake = new URL(cakeapi);
            URLConnection query = cake.openConnection();
            BufferedReader data = new BufferedReader( new InputStreamReader(query.getInputStream()));

            SAXReader reader = new SAXReader();
            Document document = reader.read(data);
            List<Node> list =  document.selectNodes("/*[name()='affiliate_export_response']/*[name()='affiliates']/*[name()='affiliate']");

            for (Node item: list) {
                String value = item.asXML();

                int eStart = value.indexOf("<email_address>"), eStop = value.indexOf("</email_address");
                email = (eStart != -1 && eStop != -1)? value.substring(eStart + 15,eStop): "";
            }
            data.close();
        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
        }
        return  email;
    }

    private static HashMap<String, Integer>  activeEmails = new HashMap<>();
    private static void updateMailchimpListOffer(String email, String offer) throws Exception{

        MailchimpClient client = new MailchimpClient(apiKey);

        try {
            int activeCount = 0;
            EditMemberMethod.CreateOrUpdate method = new EditMemberMethod.CreateOrUpdate(listId, email);
            method.status = "subscribed";
            method.merge_fields = new MailchimpObject();
            //method.merge_fields.mapping.put("OFFER", offer);
            if(offer.contains("NG")){ method.merge_fields.mapping.put("NG_ACTIVE", "1"); activeCount++; }
            if(offer.contains("KE")){ method.merge_fields.mapping.put("KE_ACTIVE", "1"); activeCount++; }
            if(offer.contains("EG")){ method.merge_fields.mapping.put("EG_ACTIVE", "1"); activeCount++; }
            if(offer.contains("MA")){ method.merge_fields.mapping.put("MA_ACTIVE", "1"); activeCount++; }
            if(offer.contains("GH")){ method.merge_fields.mapping.put("GH_ACTIVE", "1"); activeCount++; }
            if(offer.contains("CI")){ method.merge_fields.mapping.put("CI_ACTIVE", "1"); activeCount++; }
            if(offer.contains("CM")){ method.merge_fields.mapping.put("CA_ACTIVE", "1"); activeCount++; }
            if(offer.contains("TRVL")){ method.merge_fields.mapping.put("TVL_ACTIVE", "1"); activeCount++; }


            if(activeCount == 1){
                method.merge_fields.mapping.put("ACTIVE_ONE", "1");
                System.out.println(activeEmails.size());
            }else{
                method.merge_fields.mapping.put("ACTIVE_ONE", "0");
            }
            if(activeEmails.containsKey(email) ){
                method.merge_fields.mapping.put("ACTIV_MANY", "1");
            }else {
                method.merge_fields.mapping.put("ACTIV_MANY", "0");
            }

            activeEmails.put(email, activeCount);
            MemberInfo member = client.execute(method);
            System.out.println("The user active offer has been successfully updated: " + member);

        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }finally {
            client.close();
        }
    }
    private static void updateMailchimpListOfferEngagement(int offerId, String email) throws Exception{

        MailchimpClient client = new MailchimpClient(apiKey);

        try {
            EditMemberMethod.CreateOrUpdate method = new EditMemberMethod.CreateOrUpdate(listId, email);
            method.status = "subscribed";
            method.merge_fields = new MailchimpObject();
            //method.merge_fields.mapping.put("OFFER", offer);
            if(offerId == 9){ method.merge_fields.mapping.put("NG_ENGAGED", "1");  }
            if(offerId == 7){ method.merge_fields.mapping.put("KE_ENGAGED", "1");  }
            if(offerId == 8){ method.merge_fields.mapping.put("EG_ENGAGED", "1");  }
            if(offerId == 10){ method.merge_fields.mapping.put("MA_ENGAGED", "1");  }
            if(offerId == 13){ method.merge_fields.mapping.put("GH_ENGAGED", "1");  }
            if(offerId == 11){ method.merge_fields.mapping.put("CI_ENGAGED", "1");  }
            if(offerId == 15){ method.merge_fields.mapping.put("CA_ENGAGED", "1");  }
            if(offerId == 16){ method.merge_fields.mapping.put("TVL_ENGAGE", "1");  }


            MemberInfo member = client.execute(method);
            System.out.println("The user offer engagement has been successfully updated: " + member);


        }
        catch (Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }finally {
            client.close();
        }
    }

    public static void batchUpdateList(ArrayList<EditMemberMethod.CreateOrUpdate> emailList){
        MailchimpClient client = new MailchimpClient(apiKey);
        StartBatchMethod startBatchMethod = new StartBatchMethod(emailList);

        int batchId = client.execute(new StartBatchMethod(emailList));

    }

}
`

**Comment by mayorcoded** [comment]
I tried to implement it in the past method: batchUpdateList() @basiliscus  thanks

**Comment by basiliscus** [comment]
Just replace the last line with

`int batchId = client.execute(new StartBatchMethod(emailList)).id;`

**Comment by mayorcoded** [comment]
Wow, I just needed to add '.id' okay. Thanks alot @basiliscus I hold you guys in high regard
