### ISSUE TITLE
How to Create a Subscriber List in Java Using MaleOrang

### ISSUE THREAD

**Issue by simonnarang** [Ecwid/maleorang#2]
Your library is really cool, 

I'm wondering how to use this lib to Create a Subscriber List in Java

Thanks,
Simon

**Comment by simonnarang** [comment]
I am also wondering how authentication works with this wrapper, I have been looking through and am having trouble finding it

**Comment by apocheau** [comment]
Create a subscriber list does not exist yet, but I am pretty sure that contribution is welcome.

Authentication is only made through the Api key, the same as in the playground.

**Comment by basiliscus** [comment]
Hi simonnarang,

The "create list" method is not implemented yet. However, you can add its support yourself. Refer to [the example](https://github.com/Ecwid/maleorang/blob/master/src/test/java/com/ecwid/maleorang/examples/CustomMethodExample.java) or to [the pull request](https://github.com/Ecwid/maleorang/pull/1)
