### ISSUE TITLE
open_rate error com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 27.2030651341 at line 1 column 42345 path $.lists[8].stats.open_rate

### ISSUE THREAD

**Issue by mariobyn** [Ecwid/maleorang#3]
Hey,

After some time it started to give me this error.

com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 27.2030651341 at line 1 column 42345 path $.lists[8].stats.open_rate

**Comment by basiliscus** [comment]
It appears open_rate field should be a Double instead of Int

**Comment by IVIyg0t** [comment]
Hey there!  Great looking API.

I, too, am having this issue.  How do we resolve it?

**Comment by basiliscus** [comment]
The issue has been fixed in #4, thanks to @IVIyg0t

**Comment by basiliscus** [comment]
A new version 3.0-0.9.4 will appear in Maven Central in a couple of hours

**Comment by IVIyg0t** [comment]
Many thanks @basiliscus!
